project:
  type: website

website:
  title: "Welcome to My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: kkk

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



