project:
  type: website

website:
  title: "Jitvan Vij"
  navbar:
    background: black
    left:
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    center: "© 2025 Jitvan Vij"

format:
  html:
    theme: flatly
    css: styles.css
